[project]
name = "dems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "bs4>=0.0.2",
    "pytest>=9.0.2",
    "selenium",
]


